# -*- coding: utf-8 -*-
"""1st class python analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vewhoPqUtr3sEaKGjG4zpK0E-g7PQeu

```
# Introduction to python ="Hello, world"
```
"""

print("Hello world")

"""Learn Variables and Data Types"""

name = "kazi nayeem"
age = 21
height = 5.6

print(name)
print(age)
print(height)

"""**Practice Basic Operations**"""

a = 10
b = 3



print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)



# string

first = "kazi"
last = "Nayeem"

print(first + " " + last)

"""## **Understand Conditional Statements**"""

score = 33

if score > 90:
  print("Excellent")
elif score >= 70:
  print("Good")
elif score >= 33:
  print("Pass")
elif score < 33:
  print("Fail")
else:
  print("Fail")

"""**Try Loops**"""

# for loop

for i in range(10):
  print(i)

# whilte loop
count = 0
while count < 5:
    print(count)
    count += 1

"""**Work with Lists**"""

language = ["js" , "python" , "go" , "Cpp"]
for i in language:
  print(i)

# append
language.append("c")
print(language)