# -*- coding: utf-8 -*-
"""Class 2: Data Structures and Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mckYRKGXVuu80SbGP8Zx1TPP-ScvyV6d

Lists and Loops
"""

numbers = [1,2,3,4,5]
fruits = ["apple" , "mango"]

print(numbers[1])
print(fruits[0])

print(numbers[1:2])

for fruit in fruits:
    print(fruit)

"""List Comprehension"""

squares = [x**2 for x in numbers]
print(squares)

"""def function or method"""

def addition(x):
  x = x+x
  return x

addition(10)

"""fda"""

def Squire(x):
  x = x**2
  return x

results = Squire(10)
print(results)

def add_two_number(x,y):
  return x+y

result = add_two_number(10,20)
print(result)

print(add_two_number(10,20))

"""Sub list"""

language = ["java" , "kotlin" , "cpp" , "c" , "golang", "typescript"]
print(language[0:2])

"""Sub List"""

for value in language[0:2]:
  print(value)

"""Hidden index find out enumerae Function"""

for index, item in enumerate(language):
  print(f"index is {index + 1} and item is {item}")

from itertools import count
price = [133,2323,3323,4323,53232]
product = ["Mobile" , "Desktop", "Laptop" , "Tab" , "Car"]
# product.remove("Mobile")
# product
product.insert(0, "Mac")
len(product)

for product,price in zip(product,price):
  print(f"product is {product} and price is {price}")



"""# Dictionary"""

user = {"user1" : "kazi" , "user2" : "kazi2"}
print(user.keys())

"""Num py"""

import pandas as pd
import numpy as np

any = np.array([1,2,3,4,5])
print(any)

any = np.array([[1,2,3,4,5],[1,2,3,4,5]]) #2d
print(any)